### ISSUE TITLE
invalid beancount file: ValueError: '=' alignment not allowed in string format specifier

### ISSUE THREAD

**Issue by blais** [beancount/beancount#360]
**[Original report](https://bitbucket.org/blais/beancount/issue/360) by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

This invalid file leads to:

```
1970-01-01 open Assets:Cash
1970-01-01 open Equity:Adjustments

2014-04-10 txn "Adjustment"
  Assets:Cash
  Equity:Adjustments
```

```
Traceback (most recent call last):
  File "/home/tbm/.local/bin/bean-check", line 6, in <module>
    sys.exit(main())
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/scripts/check.py", line 40, in main
    extra_validations=validation.HARDCORE_VALIDATIONS)
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/loader.py", line 90, in load_file
    _log_errors(errors, log_errors)
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/loader.py", line 128, in _log_errors
    printer.print_errors(errors, file=log_errors)
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/parser/printer.py", line 444, in print_errors
    output.write(format_error(error))
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/parser/printer.py", line 414, in format_error
    error_string = '\n'.join(format_entry(entry) for entry in entries)
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/parser/printer.py", line 414, in <genexpr>
    error_string = '\n'.join(format_entry(entry) for entry in entries)
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/parser/printer.py", line 339, in format_entry
    return EntryPrinter(dcontext, render_weights)(entry)
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/parser/printer.py", line 117, in __call__
    method(obj, oss)
  File "/home/tbm/.local/lib/python3.5/site-packages/beancount/parser/printer.py", line 201, in Transaction
    oss.write(fmt(account, position_str))
ValueError: '=' alignment not allowed in string format specifier
```

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

bergamot [hg|default]:~/r/q/beancount-data/issue$ bean-check issue360.beancount 
/home/blais/r/q/beancount-data/issue/issue360.beancount:6:       You may not have more than one auto-posting per currency

   2014-04-10 * "Adjustment"
     Assets:Cash          
     Equity:Adjustments   


bergamot [hg|default]:~/r/q/beancount-data/issue$ python3
Python 3.7.2 (default, Jan 22 2019, 00:50:43) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 


What version are you using?

**Comment by blais** [comment]
**Original comment by Martin Michlmayr (Bitbucket: [tbm13](https://bitbucket.org/tbm13), GitHub: [tbm](https://github.com/tbm)).**

----------------------------------------

Python 3.5.3

Beancount 2.2.0

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

I was able to repro.
That's already been fixed in the default branch.
Just baked 2.2.1 for you.

**Comment by blais** [comment]
**Original comment by Martin Blais (Bitbucket: [blais](https://bitbucket.org/blais), GitHub: [blais](https://github.com/blais)).**

----------------------------------------

Baked 2.2.1 with fix included.

**Comment by blais** [comment]
**Original comment by Mal Morrow (Bitbucket: [malmorrow](https://bitbucket.org/malmorrow), GitHub: [malmorrow](https://github.com/malmorrow)).**

----------------------------------------

Very nice, thanks.

**Comment by alexandergogl** [comment]
Hello Martin.

When using the beancount-context (bean-doctor context) command in Spacemacs' beancount-mode then the `ValueError: '=' alignment not allowed in string format specifier` error still occurs if I leave the `Assets:Budget` posting empty. Do you have any clue why this happens?

Beancount 2.3.4 (git:5adf7b9a; 2021-03-20)
beancount-mode (git:02fe03e)

**Input:**

```
2021-01-01 open Assets:Budget
2021-01-01 open Expenses:Production

2021-06-24 ! "Producer" "Estimation"
  Assets:Budget
  Expenses:Production        2.00 M2 {500 EUR}
```

**Traceback:**

```
bean-doctor context project.beancount 73
Traceback (most recent call last):
  File "/Users/alex/.miniconda3/bin/bean-doctor", line 8, in <module>
    sys.exit(main())
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/scripts/doctor.py", line 439, in main
    function(opts.filename, opts.rest)
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/scripts/doctor.py", line 228, in do_context
    str_context = context.render_file_context(entries, options_map,
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/parser/context.py", line 59, in render_file_context
    return render_entry_context(entries, options_map, closest_entry, closest_parsed_entry)
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/parser/context.py", line 129, in render_entry_context
    printer.print_entry(parsed_entry, dcontext, render_weights=True, file=oss)
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/parser/printer.py", line 384, in print_entry
    output.write(format_entry(entry, dcontext, render_weights))
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/parser/printer.py", line 369, in format_entry
    return EntryPrinter(dcontext, render_weights, prefix=prefix)(entry)
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/parser/printer.py", line 123, in __call__
    method(obj, oss)
  File "/Users/alex/.miniconda3/lib/python3.8/site-packages/beancount/parser/printer.py", line 206, in Transaction
    oss.write(fmt(account,
ValueError: '=' alignment not allowed in string format specifier

Compilation exited abnormally with code 1 at Fri Jul  2 22:33:16
```
